### ISSUE TITLE
Player Guides

### ISSUE THREAD

**Issue by IMB11** [FabricMC/fabric-docs#4]
A more modernized version of the player section of the wiki: https://fabricmc.net/wiki/player:tutorials:start

## TODO:

- [x] Index Page
- [x] FAQ
- [x] Installing Java
	+ [x] Windows
	+ [x] #13
	+ [x] Linux
- [x] Troubleshooting
	+ [x] What are Crash Reports?
	+ [x] Uploading Logs (Vanilla Launcher (MacOS/Linux/Windows))
- [x] Installing Fabric (Vanilla Launcher)
- [x] Finding Mods (What are trustworthy sources? eg. modrinth+Curseforge+github)
- [x] Installing Mods (Vanilla Launcher)
- [x] Updating Fabric Loader (Vanilla Launcher)

**Comment by IMB11** [comment]
I would also like some opinions on the "Troubleshooting" section, there are quite a few support tags on the Fabric discord that could potentially be worth becoming pages.

**Comment by IMB11** [comment]
Most notably the binary mod search tag or some along those lines.

**Comment by JR1811** [comment]
> I would also like some opinions on the "Troubleshooting" section, there are quite a few support tags on the Fabric discord that could potentially be worth becoming pages.

It would be nice ngl... 
Basic steps were already on the old *moddedmc.wiki* including logging, debugging and hotswaping.

**Comment by IMB11** [comment]
That would probably fit better into the developer section, as that's more IDE based. These are for users wanting to use Fabric

**Comment by modmuss50** [comment]
I think we should only talk about the vanilla launcher on this docs site. The wiki is much better suited for the 3rd party launchers.
